services:
  spendly:
    build: .
    container_name: spendly
    image: edm115/spendly
    ports:
      - "60000:60000"
    env_file:
      - .env
    environment:
      SEED: "true"
    volumes:
      - spendly_db:/app/db
    restart: unless-stopped

volumes:
  spendly_db:
