allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": false
  better-sqlite3: false
  core-js: true
  esbuild: true
  prisma: false
  sharp: false
  unrs-resolver: true

dedupePeers: true

lockfileIncludeTarballUrl: true

minimumReleaseAge: 120

overrides:
  sharp: 0.35.3

resolutionMode: highest

savePrefix: ""
