allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

lockfileIncludeTarballUrl: true

overrides:
  # @nuxt/cli need to update @bomb.sh/tab
  citty: "~0.2.1"
  # blocked by peer dep in @eslint/config-inspector and dep in eslint-plugin-import-x (@nuxt/eslint-config)
  eslint: "~10.0.1"

publicHoistPattern:
  - '*vuetify*'

resolutionMode: highest

savePrefix: ''
