allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true

lockfileIncludeTarballUrl: true

publicHoistPattern:
  - '*vuetify*'

resolutionMode: highest

savePrefix: ''
