lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver

publicHoistPattern:
  - '*vuetify*'

resolutionMode: highest

savePrefix: ''
