allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': false
  better-sqlite3: true
  core-js: true
  esbuild: true
  prisma: false
  sharp: true
  unrs-resolver: true

dedupePeers: true

lockfileIncludeTarballUrl: true

overrides:
  vite: ~7.3.2

publicHoistPattern:
  - '*vuetify*'

resolutionMode: highest

savePrefix: ''
